CREATE OR REPLACE PROCEDURE DATA_RADAR.CUSTOMER_LOSSES(CUSTOMER_GUID VARCHAR(255), EVENT_TIMESTAMP TIMESTAMP)
LANGUAGE SQL 
AS 
$$
    SELECT 
        SUM(REAL_MONEY) 
    FROM
        DATA_RADAR.BIG_LOSSES as BL
    WHERE 
        BL.CUSTOMER_GUID = CUSTOMER_GUID AND ((BL.EVENT_TIMESTAMP <= EVENT_TIMESTAMP) AND (BL.EVENT_TIMESTAMP >= (EVENT_TIMESTAMP - INTERVAL '1 day')))
$$
